# Generated by Django 5.2 on 2025-05-06 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 17, 28, 49, 968534, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
